/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package quotes.api;

import org.springframework.boot.SpringApplication;
import org.springframework.boot.autoconfigure.SpringBootApplication;

@SpringBootApplication
public class Api {
	public static void main(String[] args) {
		SpringApplication.run(Api.class, args);
	}
}
