/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package quotes.api;

import org.springframework.boot.SpringApplication;
import org.springframework.boot.autoconfigure.SpringBootApplication;
import org.springframework.context.annotation.Configuration;
import org.springframework.context.annotation.EnableAspectJAutoProxy;
import org.springframework.transaction.annotation.EnableTransactionManagement;

@SpringBootApplication
@EnableAspectJAutoProxy
@EnableTransactionManagement
@Configuration
public class Api {
	public static void main(String[] args) {
		SpringApplication.run(Api.class, args);
	}
}
